version: '3'

services:

  aircompany-mysql:
    build: mysql/
    #image: mysql:latest
    restart: always
    ports:
      - "3308:3306"

  aircompany-app:
    build: .
    restart: always
    ports:
    - "8080:8080"